# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a246dfa07028385a6cae30db251af0f2854cbbfae0acc16f6b983603284438077143ed0d9765a6cf3d156307324e903ff73d10ef0fae4023715c8d792fe4dab

test:
  secret_key_base: 0d35362a6e81d141d45f9ba1a774693bd7f0fa3995dcc1390c5635be2d557d49b6a2e229b8fc218fc74aa852dc0e1a8c0d2258e6ecdbd4a43b04d6fed4f47b6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
